name: Compile

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Calculate version
        id: calculate_version
        run: |
          current_tag=${{ github.ref }}
          version=$(echo "$current_tag + 0.1" | bc)
          echo "::set-output name=version::$version"
      - name: release
        uses: actions/create-release@v1
        id: create_release
        with:
          draft: false
          prerelease: false
          release_name: v${{ steps.calculate_version.outputs.version }}
          tag_name: v${{ steps.calculate_version.outputs.version }}
          body_path: README.md
        env:
          GITHUB_TOKEN: ${{ github.token }}
      - name: upload linux artifact
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ github.token }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./lunarbox
          asset_name: lunarvm
          asset_content_type: application/octet-stream
